Cargo.toml
benches/bench.rs

This changes the bencher to criterion!
I noticed you don't run benches on CI, so I didn't add/change it. :) I also didn't change/add any benches, I just wanted to show you this neat library @undef1nd ! :)
Criterion is one of  my favorite libraries, and I hope you might enjoy it too! If not, I won't be offended if you close this.
This uses the method described in https://bheisler.github.io/criterion.rs/book/user_guide/benchmarking_with_inputs.html to cover the existing benchmarking cases.
From reading your tests and code, it seems like you may wish to have further work deriving the benchmarks from the fixtures in `tests/spec_tests`?
As for why you might prefer Criterion to `bencher`:
* You can set and compare baselines: https://bheisler.github.io/criterion.rs/book/user_guide/command_line_op …

Use criterion for benching

---

src/serializer.rs

With running `cargo clippy` locally, I got 1 error and 2 warnings. This PR will fix the warnings part.
The error is
```rust
error: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices.
--> src/serializer.rs:64:46
|
64 |     pub(crate) fn serialize_list(input_list: &List, output: &mut String) -> SFVResult<()> {
|                                              ^^^^^
|
note: the lint level is defined here
--> src/serializer.rs:63:12
|
63 |     #[deny(clippy::ptr_arg)]
|            ^^^^^^^^^^^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
```
because the `List` type is an alias-ed type, I'm not sure if we should fix it with the clippy suggestion.

Fix clippy warnings

---

src/serializer.rs

Clippy has the manual_range_contains lint
https://rust-lang.github.io/rust-clippy/master/index.html#manual_range_contains
This change converts the valid character check in `serialize_string()`
to the range format that Clippy suggests.

Update serialize_string valid char check format

---

src/serializer.rs

Clippy has the lint
https://rust-lang.github.io/rust-clippy/master/index.html#single_char_add_str
There was one instance where `push_str()` was used to add a single SP
char. Other similar code used `push`. This change switches to `push()`,
which makes things consistent, and little Mr. Clippy happy.

Fix one instance of push_str for a single char

---

tests/specification_tests.rs

On a fresh checkout I forgot to clone recursively and the tests failed because I hadn't fetched the submodule containing the json test files. The test failure message is bit cryptic, so instead lets just panic with a more useful message that the user can action.

tests: detect and warn missing spec_tests submodule

---

src/parser.rs
src/serializer.rs

Clippy runs a needless borrow lint
https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow.
This commit addresses the lint instances in `parse_bare_item()`. Once
that is done, the method itself becomes a compiler warning. So this
change also removes a mut from the signature.
Old:
pub(crate) fn parse_bare_item(mut input_chars: &mut Peekable<Chars>)
New:
pub(crate) fn parse_bare_item(input_chars: &mut Peekable<Chars>)
This has the effect of making the function signature more aligned with
all the other parse_xyz methods.

Address Clippy "needless borrow" lint

---

tests/specification_tests.rs

Previously, a noop_method_call warning was emitted in these instances:
the type `str` does not implement `Clone`, so calling `clone` on `&str` copies the reference, which does not do anything and can be removed

Remove no-op clone calls in specification tests

---

tests/specification_tests.rs

This requires tests covering RFC 9651 Dates and Display Strings to be skipped.

Update to latest specification tests

---

Cargo.toml
src/parser.rs
src/serializer.rs
src/utils.rs
tests/specification_tests.rs

Previously, due to the way the `data-encoding` crate works, `=` was ignored anywhere it occurred, rather than only being treated as a padding byte. Unfortunately, this wasn't detected before due to the lack of specification-test coverage prior to
https://github.com/httpwg/structured-field-tests/pull/94.
In this change we replace `data-encoding` with the `base64` crate, allowing us to fix this behavior, which should require a version bump.

Stop allowing non-terminal padding bytes within byte sequences

---

src/serializer.rs
src/test_serializer.rs

Per Step 9 of https://httpwg.org/specs/rfc8941.html#ser-decimal, only the significant digits of a decimal's fractional component are serialized.
Previously, this caused a decimal like `123.10` to be serialized verbatim rather than `123.1`. This was not caught by the specification tests because the parsing function happens to normalize the parsed value itself, and unfortunately the serialization-only specification tests cannot cover this case because there is no guarantee that a JSON number `123.10` will retain the trailing `0` on parsing.
In any case, this crate should not assume that a given decimal is already normalized during serialization.

Discard insignificant digits from decimals during serialization

---

src/lib.rs
src/parser.rs
src/serializer.rs
src/test_parser.rs

- The documentation for its lone method indicated that it shouldn't be called externally
- Its method was only callable if the trait was `use`d
- It was only meant to be implemented for types defined in the crate, but was not sealed
- The public `Parser` struct already provides the same functionality
- Its lone method's interface exposed internal representation of the parser (`&mut Peekable<Chars>`), which may be changed in the future to accommodate things like copy-less parsing or configurations like RFC 9651

Remove public export of ParseValue trait

---

.github/workflows/ci-workflow.yml
fuzz/.gitignore
fuzz/Cargo.toml
fuzz/fuzz_targets/parse_dictionary.rs
fuzz/fuzz_targets/parse_item.rs
fuzz/fuzz_targets/parse_list.rs

For now in CI we only build the fuzz targets, rather than actually run them, which can be done locally using:
```sh
cargo +nightly fuzz run parse_dictionary
```

Add basic fuzzers for parsing functions

---

src/lib.rs

Otherwise these do not show up in the documentation, making them difficult to use.

Export RefInnerListSerializer and RefParameterSerializer

---

.github/workflows/ci-workflow.yml

Without this, it's easy for targets like benchmarks to bitrot.

Check all targets on build

---

src/parser.rs

In addition to making it easier to track input positions (which will benefit #126), this will also enable future optimizations to reduce the number of allocations.
For example, in this PR itself we avoid unnecessary `Vec<u8>` creation during byte-sequence parsing, and in the future tokens and keys could be returned as `&str` and strings as `Cow<str>`.

Replace iterator-based parsing with slice indexing

---

fuzz/fuzz_targets/parse_dictionary.rs
fuzz/fuzz_targets/parse_item.rs
fuzz/fuzz_targets/parse_list.rs
src/error.rs
src/lib.rs
src/parser.rs
src/ref_serializer.rs
src/serializer.rs
src/test_parser.rs
src/test_serializer.rs
src/utils.rs
tests/specification_tests.rs

Wrap errors in a new struct type and report parsing-failure positions

---

src/lib.rs
src/parser.rs
src/ref_serializer.rs
src/serializer.rs

1. Replace most uses of `unwrap` with `?`
2. Use raw strings to avoid escaping quotes and to make serialized values directly copy-pasteable

Improve readability of doc examples

---

Cargo.toml
benches/bench.rs
fuzz/Cargo.toml
fuzz/fuzz_targets/parse_dictionary.rs
fuzz/fuzz_targets/parse_item.rs
fuzz/fuzz_targets/parse_list.rs
fuzz/fuzz_targets/roundtrip_dictionary.rs
fuzz/fuzz_targets/roundtrip_item.rs
fuzz/fuzz_targets/roundtrip_list.rs
src/decimal.rs
src/integer.rs
src/key.rs
src/lib.rs
src/parser.rs
src/ref_serializer.rs
src/serializer.rs
src/string.rs
src/test_decimal.rs
src/test_integer.rs
src/test_key.rs
src/test_parser.rs
src/test_serializer.rs
src/test_string.rs
src/test_token.rs
src/token.rs
src/utils.rs
tests/integration_tests.rs
tests/specification_tests.rs

This is an updated version of #102 that takes the following approach:
1. `BareItem` and `RefBareItem` contain only fully validated types.
2. Dictionary and parameter keys are likewise fully validated.
3. A number of helpers based on `Into` and `TryInto` simplify creation of these types from unvalidated inputs, including at compile-time using `const fn`.
4. Parsing produces these fully validated types.
5. Serialization accepts only these fully validated types, making serialization in general infallible (the only real errors being empty list and empty dictionary) and presumably improving performance in the likely common case that components are fully validated at compile time.
6. `rust_decimal::Decimal` is replaced with an `sfv::Decimal` type that simply wraps the new `Integer` type, as an …

Use strong types for key and bare item integer, decimal, token, and string

---

benches/bench.rs
src/key.rs
src/ref_serializer.rs
src/serializer.rs
src/test_serializer.rs

1. Ensure that serializers can be used with owned and borrowed strings. This was an oversight in #133.
2. Share the serialization code between fully parsed structures and the incremental serializers.
3. Remove the unnecessary `Ref` prefix from the serializer types.

Reorganize serializers

---

.github/workflows/ci-workflow.yml
Cargo.toml
src/lib.rs
src/parser.rs
src/ref_serializer.rs
src/serializer.rs
src/test_parser.rs
src/test_serializer.rs

For users who only need to parse or serialize using the visitor traits, this eliminates a dependency.

Make indexmap an optional dependency

---

Cargo.toml

This eliminates a `cargo audit` warning about a transient dependency on the unmaintained `atty` crate.

Update criterion dev dependency to 0.5.1

---

benches/bench.rs
src/lib.rs
src/ref_serializer.rs
src/serializer.rs

These types can serialize complete strings, so the prefix is meaningless.

Remove redundant Ref prefix from serializer types

---

Cargo.toml
README.md
fuzz/Cargo.toml
fuzz/fuzz_targets/input.rs
fuzz/fuzz_targets/parse_dictionary.rs
fuzz/fuzz_targets/parse_item.rs
fuzz/fuzz_targets/parse_list.rs
src/date.rs
src/decimal.rs
src/integer.rs
src/key.rs
src/lib.rs
src/parsed.rs
src/parser.rs
src/ref_serializer.rs
src/serializer.rs
src/string.rs
src/test_parser.rs
src/test_serializer.rs
src/token.rs
src/visitor.rs
tests/specification_tests.rs

1. `GenericBareItem` has two additional variants: `Date` and `DisplayString`.
2. Parsing accepts a `Version` enum that controls whether dates and display strings are permitted. The newer RFC 9651 is the default.
3. Parsing always propagates errors based on the version.
4. Serialization always operates under RFC 9651. It is the API consumer's responsibility to avoid serialization of `Date` and `DisplayString` when using RFC 8941.
Fixes #119

Replace RFC 8941 with RFC 9651 as crate's default version

---

Cargo.toml

Without this change, specifying `--no-default-features --features=arbitrary` still causes `indexmap` to be built.

Do not enable indexmap dependency unless something else enables it

---

Cargo.toml

If the `tests` directory is excluded, these should be too.

Exclude benches and fuzz directories from publication

---

tests/specification_tests.rs

Locally this reduced runtime from 1.3 seconds to 0.1 seconds.

Use buffer reader for specification tests

---

src/parser.rs
src/test_parser.rs

They have the same comma-separated format.

Extract common logic for parsing list and dictionary

---

benches/bench.rs
fuzz/fuzz_targets/roundtrip_dictionary.rs
fuzz/fuzz_targets/roundtrip_item.rs
fuzz/fuzz_targets/roundtrip_list.rs
src/lib.rs
src/parser.rs
src/ref_serializer.rs
src/serializer.rs
src/test_ref_serializer.rs
src/test_serializer.rs
tests/specification_tests.rs

We also make `Item`'s `SerializeValue` implementation infallible using an associated type.
Fixes #170

Replace Result with Option in list/dictionary serialization

---

src/parsed.rs
src/parser.rs
src/test_parser.rs
src/visitor.rs

This changes the trait definitions to break the 1:1 correlation between the lifetime of the input and the lifetime of the various visitor traits.  Instead, the lifetime of any visitor that is returned is tied back to the visitor that created it.
This enables the sorts of implementation pattern that you see in the tests here.  It had no effect on the internal use of visitors, other than to change the method declarations.
Closes #179.
(In reviewing this, I realize that I messed with the use statements; I have `group_imports=StdExternalCrate` set on rustfmt in my environment.  Happy to revert that if house style is different; though you should definitely move to that setting; formatting `use` is not a good use of anyone's time.)

Rework the lifetimes on visitors

---

src/test_parser.rs
src/visitor.rs

Implement forwarding visitors for Option<V>

---

benches/bench.rs
src/date.rs
src/decimal.rs
src/integer.rs
src/key.rs
src/parsed.rs
src/parser.rs
src/ref_serializer.rs
src/serializer.rs
src/string.rs
src/test_decimal.rs
src/test_integer.rs
src/test_key.rs
src/test_parser.rs
src/test_ref_serializer.rs
src/test_serializer.rs
src/test_string.rs
src/test_token.rs
src/token.rs
src/visitor.rs
tests/specification_tests.rs

These were not uniformly easy.  There are a couple of cases where the public API changes slightly, so this should be a new dot release.
Those changes are mostly through the inclusion of `#[must_use]` in a bunch of places. Using code will then get warnings when they throw values away.
The main problem I found there was that the serializer code relied on a Drop implementation in a couple of places.  I personally don't like that very much, so I added `#[must_use]` anyway.  Using code probably isn't exposed to this detail, even if they using custom serialization arrangements, as it was only test code that had to add a bunch of useless bindings to deal with this.  Still, this is worth noting.
This does not enable `clippy::pedantic`, but that could be done after these changes land.

Fix clippy::pedantic errors

---

src/parser.rs
src/test_parser.rs

Remove unnecessary lifetime constraint from parse_dictionary_with_visitor

---

src/parsed.rs
src/parser.rs
src/test_parser.rs
src/visitor.rs

The original motivating example for them was erroneous, relying on an unintentional use of a single lifetime shared between the input and an otherwise irrelevant reference.
We retain the tests to demonstrate that the original trait changes in #180 were unnecessary.
CC #179

Revert lifetime changes from #180

---

src/decimal.rs
src/error.rs
src/integer.rs
src/parser.rs
src/string.rs
src/test_decimal.rs
src/test_parser.rs

This simplifies testing, reduces the size of the Error type, and will make it easier to expose structured information about them in the future.

Use enum for internal representation of errors
